### ISSUE TITLE
安装插件后打开报错

### ISSUE THREAD

**Issue by Helen-Guo** [fuxiuyuan/AndroidCodeGenerator#2]
打开报错，导致我原来系统的生成get和set方法的对话框都打不开了
scala/runtime/NonLocalReturnControl
java.lang.NoClassDefFoundError: scala/runtime/NonLocalReturnControl
    at com.fuxy.android.ide.plugin.generate.BaseAndroidGenerateCodeAction.isValidForClass(BaseAndroidGenerateCodeAction.scala:19)
    at com.intellij.codeInsight.generation.actions.BaseGenerateAction.isValidForFile(BaseGenerateAction.java:65)
    at com.fuxy.android.ide.plugin.generate.initialize.InitViewAction.isValidForFile(InitViewAction.scala:21)
    at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:101)
    at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:97)
    at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:243)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.appendAction(PopupFactoryImpl.java:934)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.appendActionsFromGroup(PopupFactoryImpl.java:924)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.buildGroup(PopupFactoryImpl.java:860)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:257)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:214)
    at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:194)
    at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:168)
    at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:296)
    at com.intellij.codeInsight.generation.actions.GenerateAction.actionPerformed(GenerateAction.java:38)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:483)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: scala.runtime.NonLocalReturnControl PluginClassLoader[com.fuxy.android.ide.plugin, 1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more

**Comment by shaoqianqian** [comment]
me too
